[package]
name = "billion_d4"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
clap = { version = "4.5.49", features=["derive"]}
colored = "3.0.0"
fastrand = "2.3.0"
flume = "0.11.1"
indicatif = "0.18.3"
pollster = "0.4.0"
rayon = "1.11.0"
wgpu = "27.0.1"
